name: Branch Naming Policy Check and Validate new changes

on:
    pull_request:
        types: [opened, synchronize]
        branches: [main]
        paths:
            - "force-app/**"

permissions:
    id-token: write
    contents: write
    packages: write

jobs:
    branch-naming-policy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run Branch Naming Policy Action
              uses: nicklegan/github-repo-branch-naming-policy-action@v1.1.0
              if: github.ref_type == 'branch'
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  regex: "^(CRM)-([0-9]+)-([a-zA-Z]+)"

    format-lint:
        runs-on: ubuntu-latest
        needs: branch-naming-policy
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - name: "Checkout source code"
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: "Install npm dependencies"
              run: HUSKY=0 npm ci

            - name: "Code formatting verification with Prettier"
              run: npm run prettier:verify

            - name: "Lint Lightning Web Components / Aura Components"
              run: npm run lint

    validate-on-sit-org:
        runs-on: ubuntu-latest
        needs: format-lint
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: "14"

            - name: "Checkout source code"
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: "Read PR Body"
              env:
                  PR_BODY: ${{github.event.pull_request.body}}
              run: |
                  echo $PR_BODY > ./pr_body.txt
                  node ./parsePR.js              
                  TESTS=$(cat testsToRun.txt)       
                  echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
                  - name: Install NPM
                  run: |
                      npm install

            - name: Install SFDX
              run: |
                  npm install --global sfdx-cli
                  sfdx --version

            - name: Install sfdx git delta
              run: |
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins
